- menu_name: "Contact us"

- name: "The NetCreate Team"
  url: "/contact/"
  title: "Contact"
  
- name: "Inquirium Design + Development for Learning"
  url: "http://www.inquirium.net"
  title: "Inquirium Design + Development for Learning"

#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  title: "Sitemap for Google Webmaster Tools"
